#!/bin/bash

pushd . || exit 1
cd ~/Downloads || exit 1
cp fml.jam fml.zip
rm -rf fml
mkdir fml
cd fml
unzip ../fml.zip
popd
sleep 0.3
data=$(go run main.go)
{
  echo '\\documentclass[1in]{article}'
  echo '\\usepackage{graphicx} % Required for inserting images'
  echo '\\usepackage{tikz}'
  echo '\\title{aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}'
  echo '\\begin{document}'
  echo '\\eject'
  echo '\\pdfpagewidth=60in \pdfpageheight=60in'
  printf '%s\n' "$data"
  echo '\\end{document}'
} | pbcopy
