#!/bin/bash

data=$(go run main.go -o "~/Downloads/fml.tex" "~/Downloads/fml.jam")
{
  echo '\\documentclass[1in]{article}'
  echo '\\usepackage{graphicx} % Required for inserting images'
  echo '\\usepackage{tikz}'
  echo '\\title{aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}'
  echo '\\begin{document}'
  echo '\\eject'
  echo '\\pdfpagewidth=60in \pdfpageheight=60in'
  cat ~/Downloads/fml.tex
  echo '\\end{document}'
} | pbcopy
